### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by radekg** [erlware/rebar_vsn_plugin#24]
Is this repo still maintained?

**Comment by ericbmerritt** [comment]
It is. It just hasn't needed much change for a very long time.

**Comment by radekg** [comment]
Cool, I was asking because of the hanging pull request for which there is no action for a long time. Great work btw. I'm wondering, would you consider accepting a PR which would read current version from a VERSION file?

**Comment by ericbmerritt** [comment]
Now that is just due to githubs bad notification scheme. Its only recently that I got my mail rules setup well enough to see notifications :/

Well, the main goal of this is to be able to produce a valid semver. It does that right now by leveraging git. The problem with a version file is that there is no easy way to ensure that it is valid. That is that there is only ever one version for one change. It may be possible to take the version in the version file as a base and look for the last commit that changed it and then conver that to a patch version. That would probably be accetable and then we are only replacing the tag with a version in the version file while still retaining the invariant that every version is immutable.

**Comment by radekg** [comment]
Sounds reasonable. Thank you for the explanation.
